### ISSUE TITLE
[Bug report] CAU = 0.3.5 does‘t work with SDK <= 3.7.6

### ISSUE THREAD

**Issue by ColorlessColor** [anatawa12/ContinuousAvatarUploader#95]
```
Packages\com.anatawa12.continuous-avatar-uploader\Editor\Uploader.cs(570,26): error CS0117: 'VRCApi' does not contain a definition for 'ContentUploadConsent'

Packages\com.anatawa12.continuous-avatar-uploader\Editor\Uploader.cs(570,51): error CS0246: The type or namespace name 'VRCAgreement' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by anatawa12** [comment]
Oh I forgot to check apis are new or not.
